services:
  web:
    image: jurisajzew/pkv-backend:latest
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn pkv_backend.wsgi:application
      --bind 0.0.0.0:8000
      --timeout 120
      --worker-class gthread
      --threads 4
      "
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      PYTHONUNBUFFERED: 1
